INSERT INTO public.tours (id, slug, name, description, total_duration_minutes)
VALUES (
  '00000000-0000-0000-0000-000000000001',
  'sacsayhuaman',
  'Sacsayhuamán — Fortaleza del Sol',
  'Recorré la imponente fortaleza ceremonial inca. Escuchá el Cusco como lo cuenta su gente.',
  45
) ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.tour_stops (id, tour_id, "order", name, description, latitude, longitude, radius_meters, audio_src, duration_seconds, cultural_context)
VALUES
  ('00000000-0000-0000-0000-000000000101', '00000000-0000-0000-0000-000000000001', 1, 'Murallas Ciclópeas', 'Imponentes muros de piedra de hasta 6 metros de altura, construidos con bloques megalíticos de hasta 100 toneladas.', -13.5078, -71.9815, 15, '/voices/female/parada_1_female.mp3', 71, 'Estos muros representan el dominio inca de la ingeniería sísmica. Las piedras encajan con superficies curvas y 12 ángulos distintos, lo que las hace resistentes a terremotos. Cada bloque fue tallado por mitayos (trabajadores rotativos) que entendían la piedra como un ser vivo al que habían que "vestir" respetando su forma natural.'),
  ('00000000-0000-0000-0000-000000000102', '00000000-0000-0000-0000-000000000001', 2, 'Torreón de Muyucmarca', 'Torre circular de origen inca. Su nombre en quechua significa "lugar redondo".', -13.5085, -71.9820, 20, '/voices/female/parada_2_female.mp3', 93, 'Las torres circulares como Muyucmarca tenían propósitos duales: defensivos (control visual del valle) y ceremoniales (observación astronómica durante el solsticio). Los incas alineaban sus estructuras con los cerros sagrados y eventos celestes.'),
  ('00000000-0000-0000-0000-000000000103', '00000000-0000-0000-0000-000000000001', 3, 'Sacsayhuamán — Fortaleza del Sol', 'El corazón del complejo. Fortaleza ceremonial dedicada al Inti (Sol).', -13.5075, -71.9825, 25, '/voices/female/parada_3_female.mp3', 97, 'Los muros zigzagueantes no son solo decorativos: cada saliente y entrante cumple una función acústica y estructural. En las ceremonias, el sonido de los pututos (caracolas) resonaba rebotando en los ángulos, creando un efecto envolvente que amplificaba la experiencia espiritual.'),
  ('00000000-0000-0000-0000-000000000104', '00000000-0000-0000-0000-000000000001', 4, 'Plaza del Inca', 'Espacio ceremonial con vista panorámica del Valle Sagrado.', -13.5068, -71.9830, 20, '/voices/female/parada_4_female.mp3', 97, 'Esta plaza era el escenario del Inti Raymi original, donde miles de personas se congregaban para honrar al Sol. El espacio fue diseñado para que el sonido viajara sin distorsión, permitiendo que las palabras del Sapa Inca llegaran a toda la concurrencia.'),
  ('00000000-0000-0000-0000-000000000105', '00000000-0000-0000-0000-000000000001', 5, 'Templo de la Luna', 'Estructura ceremonial dedicada a Quilla, la diosa Luna.', -13.5060, -71.9820, 25, '/voices/female/parada_5_female.mp3', 107, 'Quilla era la contraparte femenina del Inti, asociada con los ciclos menstruales, las mareas y las cosechas. Las mujeres incas realizaban aquí ceremonias de agradecimiento por la fertilidad de la tierra. Los incas medían el tiempo observando las fases de Quilla.'),
  ('00000000-0000-0000-0000-000000000106', '00000000-0000-0000-0000-000000000001', 6, 'Túneles Subterráneos', 'Red de pasajes que conectan diferentes partes del complejo.', -13.5065, -71.9805, 20, '/voices/female/parada_6_female.mp3', 116, 'El Ukhu Pacha (mundo subterráneo) era tan importante como el mundo de arriba. Estos túneles conectaban espacios ceremoniales y permitían el tránsito de sacerdotes entre templos sin ser vistos por los fieles, añadiendo misticismo a las ceremonias.'),
  ('00000000-0000-0000-0000-000000000107', '00000000-0000-0000-0000-000000000001', 7, 'Mirador Panorámico', 'Punto más alto del recorrido con vista de 360° del Valle Sagrado.', -13.5070, -71.9795, 20, '/voices/female/parada_7_female.mp3', 93, 'Desde aquí se entiende por qué los incas eligieron este lugar. El valle entero es un libro abierto: cada montaña (apu) tiene su nombre y su historia. El Ausangate al sur, el Salkantay al oeste — los apus más sagrados vigilan el valle.'),
  ('00000000-0000-0000-0000-000000000108', '00000000-0000-0000-0000-000000000001', 8, 'Roca Sagrada', 'Formación rocosa ceremonial tallada por los incas.', -13.5075, -71.9790, 15, '/voices/female/parada_8_female.mp3', 80, 'Los incas no tallaban la roca al azar. Cada ángulo y cada sombra proyectada tenía un significado calendárico. Durante el solsticio de invierno, la sombra de esta roca señala exactamente el centro ceremonial, marcando el momento preciso del renacimiento del Inti.'),
  ('00000000-0000-0000-0000-000000000109', '00000000-0000-0000-0000-000000000001', 9, 'Altar Ceremonial', 'Plataforma ceremonial donde se realizaban ofrendas a la Pachamama.', -13.5080, -71.9800, 15, '/voices/female/parada_9_female.mp3', 104, 'La ofrenda no era un simple ritual: era un contrato de reciprocidad. Los incas ofrecían lo mejor de sus cosechas y tejidos a cambio de la protección de la Pachamama. Esta relación de reciprocidad (ayni) era la base de toda la cosmovisión andina: dar y recibir en equilibrio.')
ON CONFLICT DO NOTHING;

INSERT INTO public.translations (namespace, key, value, lang) VALUES
  ('common', 'close', 'Cerrar', 'es'),
  ('common', 'loading', 'Cargando...', 'es'),
  ('common', 'error', 'Error', 'es'),
  ('download', 'button', 'Descargar ahora', 'es'),
  ('download', 'keepOpen', 'Mantené esta pantalla abierta durante la descarga', 'es'),
  ('download', 'aria', 'Descargar tour', 'es'),
  ('download', 'title', 'Descarga el tour antes de llegar', 'es'),
  ('loadMap', 'loading', 'Cargando mapa...', 'es'),
  ('location', 'orSimulate', 'O simulá una ubicación de prueba:', 'es'),
  ('location', 'gpsActive', 'GPS activo', 'es'),
  ('location', 'pois', 'Puntos de interés', 'es'),
  ('location', 'tourStops', 'Paradas del tour', 'es'),
  ('location', 'outOfRange', 'fuera de rango', 'es'),
  ('location', 'activateGps', 'Activar GPS', 'es'),
  ('location', 'enableGps', 'Activá tu ubicación para verte en el mapa', 'es'),
  ('location', 'title', 'Mapa del tour', 'es'),
  ('location', 'inRange', 'EN RANGO', 'es'),
  ('login', 'title', 'Bienvenido', 'es'),
  ('login', 'subtitle', 'Escuchá el Cusco como lo cuenta su gente', 'es'),
  ('login', 'email', 'Correo electrónico', 'es'),
  ('login', 'emailPlaceholder', 'tu@email.com', 'es'),
  ('login', 'password', 'Contraseña', 'es'),
  ('login', 'continue', 'Continuar', 'es'),
  ('login', 'loggingIn', 'Ingresando...', 'es'),
  ('login', 'noAccount', '¿No tenés cuenta?', 'es'),
  ('login', 'signUp', 'Registrate', 'es'),
  ('login', 'or', 'o', 'es'),
  ('offline', 'mode', 'Sin conexión — modo offline', 'es'),
  ('offline', 'restored', 'Conexión restablecida', 'es'),
  ('player', 'next', 'Siguiente: {{name}}', 'es'),
  ('player', 'back', 'Volver', 'es'),
  ('player', 'offline', 'Sin conexión', 'es'),
  ('player', 'endOfTour', 'Fin del tour', 'es'),
  ('player', 'faq', 'FAQ', 'es'),
  ('player', 'suggest', 'Sugerir', 'es'),
  ('player', 'bot', 'Bot', 'es'),
  ('player', 'playing', 'Reproduciendo', 'es'),
  ('pwa', 'title', 'Guarda Rimay en tu pantalla de inicio', 'es'),
  ('pwa', 'subtitle', 'Accede sin abrir el navegador. Tu tour queda guardado.', 'es'),
  ('pwa', 'iosInstructions', 'Toca', 'es'),
  ('pwa', 'androidInstructions', 'Toca ⋮ → "Agregar a pantalla de inicio"', 'es'),
  ('pwa', 'addToHome', '"Agregar a pantalla de inicio"', 'es'),
  ('pwa', 'gotIt', 'Entendido', 'es'),
  ('pwa', 'notNow', 'Ahora no', 'es'),
  ('pwa', 'aria', 'Agregar a pantalla de inicio', 'es'),
  ('splash', 'stops', 'Tour de {{count}} paradas', 'es'),
  ('splash', 'duration', '{{min}} min aprox.', 'es'),
  ('splash', 'start', 'Iniciar narración', 'es'),
  ('splash', 'viewLocation', 'Ver ubicación', 'es'),
  ('splash', 'viewStops', 'Ver todas las paradas', 'es'),
  ('splash', 'tourStopsTitle', 'Paradas del tour', 'es')
ON CONFLICT (namespace, key, lang) DO UPDATE SET value = EXCLUDED.value;

INSERT INTO public.translations (namespace, key, value, lang) VALUES
  ('common', 'close', 'Close', 'en'),
  ('common', 'loading', 'Loading...', 'en'),
  ('common', 'error', 'Error', 'en'),
  ('download', 'button', 'Download now', 'en'),
  ('download', 'keepOpen', 'Keep this screen open during download', 'en'),
  ('download', 'aria', 'Download tour', 'en'),
  ('download', 'title', 'Download the tour before you arrive', 'en'),
  ('loadMap', 'loading', 'Loading map...', 'en'),
  ('location', 'orSimulate', 'Or simulate a test location:', 'en'),
  ('location', 'gpsActive', 'GPS active', 'en'),
  ('location', 'pois', 'Points of interest', 'en'),
  ('location', 'tourStops', 'Tour stops', 'en'),
  ('location', 'outOfRange', 'out of range', 'en'),
  ('location', 'activateGps', 'Activate GPS', 'en'),
  ('location', 'enableGps', 'Enable your location to see yourself on the map', 'en'),
  ('location', 'title', 'Tour map', 'en'),
  ('location', 'inRange', 'IN RANGE', 'en'),
  ('login', 'title', 'Welcome', 'en'),
  ('login', 'subtitle', 'Listen to Cusco as told by its people', 'en'),
  ('login', 'email', 'Email', 'en'),
  ('login', 'emailPlaceholder', 'you@email.com', 'en'),
  ('login', 'password', 'Password', 'en'),
  ('login', 'continue', 'Continue', 'en'),
  ('login', 'loggingIn', 'Signing in...', 'en'),
  ('login', 'noAccount', 'Don''t have an account?', 'en'),
  ('login', 'signUp', 'Sign up', 'en'),
  ('login', 'or', 'or', 'en'),
  ('offline', 'mode', 'Offline mode', 'en'),
  ('offline', 'restored', 'Connection restored', 'en'),
  ('player', 'next', 'Next: {{name}}', 'en'),
  ('player', 'back', 'Back', 'en'),
  ('player', 'offline', 'Offline', 'en'),
  ('player', 'endOfTour', 'End of tour', 'en'),
  ('player', 'faq', 'FAQ', 'en'),
  ('player', 'suggest', 'Suggest', 'en'),
  ('player', 'bot', 'Bot', 'en'),
  ('player', 'playing', 'Playing', 'en'),
  ('pwa', 'title', 'Save Rimay to your home screen', 'en'),
  ('pwa', 'subtitle', 'Access without opening the browser. Your tour is saved.', 'en'),
  ('pwa', 'iosInstructions', 'Tap', 'en'),
  ('pwa', 'androidInstructions', 'Tap ⋮ → "Add to home screen"', 'en'),
  ('pwa', 'addToHome', '"Add to home screen"', 'en'),
  ('pwa', 'gotIt', 'Got it', 'en'),
  ('pwa', 'notNow', 'Not now', 'en'),
  ('pwa', 'aria', 'Add to home screen', 'en'),
  ('splash', 'stops', '{{count}}-stop tour', 'en'),
  ('splash', 'duration', '~{{min}} min', 'en'),
  ('splash', 'start', 'Start tour', 'en'),
  ('splash', 'viewLocation', 'View location', 'en'),
  ('splash', 'viewStops', 'View all stops', 'en'),
  ('splash', 'tourStopsTitle', 'Tour stops', 'en')
ON CONFLICT (namespace, key, lang) DO UPDATE SET value = EXCLUDED.value;
